### PR TITLE
Move Node.js SemVer API into a separated plug-in

### PR DESCRIPTION
**Pull request by vrubezhny**
The API for Node.js SemVer realization is moved into a separated plug-in due to allow Bower plug-ins not to depend on Node.js Core plug-in.

Also, the .settings/ folders were removed from the repository for Bower plug-ins.

Signed-off-by: vrubezhny vrubezhny@exadel.com

### CODE REVIEW

**Comment by dgolovin** [comment]
Is there any chance someone wouldl take a look at this PR soon?
Thanks!

**Comment by sbegaudeau** [comment]
Hi,

Sorry for the delay, I was away for the holidays. I will have a look at the issues that have been opened on the project today. In order to contribute easily this work in JSDT it would be better to try to contribute things one by one starting with my work on bower. Yet I don't think that creating a new plugin for five classes is the best way to go. I will re-structure this work to create separate branches for separate contributions. My work on this repository contains too many things on a same branch / commit. I will separate everything and clean my code for the contribution of the bower part only starting with the engine and actions.

Have a look at the branch named "bower", it should contain only the bower-related code and the nodejs semver code in a state that should be ok for you (it can be easily rebased on the current state of the master branch of the jsdt repository). I will create additional branches for the nodejs launch configuration and another one for npm-related code and we will thus be able to work on those topics with a minimal impact on the others starting with bower since it only requires code already used within the Eclipse Foundation like JGit or JUnit.

On another topic, why would you want to remove the settings folders? If you want to have some consistency in the coding style of all the contributors, a common set of rules is needed.

Regards,

Stephane Bégaudeau, Obeo

**Comment by sbegaudeau** [comment]
The Node.js launch configuration is now available on its dedicated branch.

**Comment by vrubezhny** [comment]
Stephane,

Contributing the code as a separated/smaller projects is great point and exactly is what we need. I'll look at the bower repo. Thanks!

The .settings folder often contains the settings that are specific to a certain Eclipse instance. But tycho/maven build doen't use it. As such some things that can be built in your Eclipse (because of having some set up saved in .settings) could break the whole WTP build. Using of wrong API like Java 8 is one of such problems. Also, IMHO, there shouldn't be 'individual' settings in a common/shared project. I'm going to drop the .setting folders from all the JSDT plug-ins in near future. All should be able to build/test by using mvn clean install or mvn clean verify commands - not by building the projects within Eclipse instance.

**Comment by sbegaudeau** [comment]
I disagree with you on the topic of the settings, those files contain lots of configuration that are critical to have an efficient collaboration on a project. Those settings contains way more information than just the Java Runtime needed and those information are needed like the settings of the formatter, the indentation of the code and the warnings and errors that you want to highlight in the editor (for example to activate the additional tracking of potential memory leaks by the JDT).

On the topic of the build, if you remove those settings, I can still use Java 8 code in a project and it will build in my Eclipse and not in the maven build so I don't see why they should be removed

> Also, IMHO, there shouldn't be 'individual' settings in a common/shared project.

They are not individual settings, they are the settings needed to edit the project properly for all contributors. How would you share the settings of the formatter (for example) across the contributors of the project otherwise? Or do you disagree with the fact that all developers should share the exact same settings for the formatter of the project?

Almost all the projects of the Eclipse Foundation are using this mechanism to enforce some kind of settings for all their contributors like the formatter or compiler settings (even the main WTP project):
- JDT: http://git.eclipse.org/c/jdt/eclipse.jdt.core.git/tree/org.eclipse.jdt.core/.settings
- CDT: http://git.eclipse.org/c/cdt/org.eclipse.cdt.git/tree/core/org.eclipse.cdt.core/.settings
- Equinox: http://git.eclipse.org/c/equinox/rt.equinox.bundles.git/tree/bundles/org.eclipse.equinox.common/.settings
- WTP: http://git.eclipse.org/c/m2e-wtp/org.eclipse.m2e.wtp.git/tree/org.eclipse.m2e.wtp/.settings
- WTP JPA: http://git.eclipse.org/c/m2e-wtp/org.eclipse.m2e.wtp.jpa.git/tree/org.eclipse.m2e.wtp.jpa/.settings

If you want to activate additional compiler check in Eclipse thanks to those settings, you can also enforce them during the build in Tycho using:

```
<plugin>
  <groupId>org.eclipse.tycho</groupId>
  <artifactId>tycho-compiler-plugin</artifactId>
  <version>${tycho-version}</version>
  <configuration>
    <compilerArguments>
      <properties>${project.basedir}/.settings/org.eclipse.jdt.core.prefs</properties>
    </compilerArguments>
  </configuration>
</plugin>
```

**Comment by vrubezhny** [comment]
> On the topic of the build, if you remove those settings, I can still use Java 8 code in a project and it will build in my Eclipse and not in the maven build so I don't see why they should be removed

The answer is here. You cannot use Java 8 in WTP and JSDT projects because it's not allowed. All the projects must be built by tycho by the same commands and have not to use some special settings like JDK or library paths etc. Off course, the settings may help to properly set up some things like formatter and indentation settings, and event help with finding on memory leaks, but at the moment (speaking of JSDT) they make it sometime impossible to just clone-import-build JSDT plug-ins by Eclipse. Nobody uses/updates these existing settings for a long time for JSDT project so these settings become a problem. That's why I feel a need to drop them and use the same project independent settings for all the JSDT projects. Code formatting and indenting rules are pretty easy to pick up from JDT so I don't see it as a big problem. But even in this - look at the JSDT code - it's very bad formatted (even with using of .settings in the past) and has improper JDK versions set in .settings - so .settings didn't help here. This days (with 3.6/3.7 versions) we're moving the build to maven/tycho, and I don't see any reason to save those (mostly obsolete) settings.

> If you want to activate additional compiler check in Eclipse thanks to those settings, you can also enforce them during the build in Tycho using

Off course, we can. We don't need it at the moment. It might make sense for very individual projects, but I don't know such ones in JSDT at the moment.
I'm not against using .settings at all. But now the usage of .settings in JSDT is far far away of something that can be called "proper".

**Pull request closed without merging**
